FROM eclipse-temurin:17-jdk-alpine

WORKDIR /app

ARG JWT_SECRET_KEY
ARG SPRING_DATASOURCE_URL
ARG SPRING_DATASOURCE_USERNAME
ARG SPRING_DATASOURCE_PASSWORD
ARG SUPPORT_EMAIL
ARG APP_PASSWORD
ARG GOOGLE_CLIENT_ID
ARG GOOGLE_CLIENT_SECRET
ARG GH_CLIENT_ID
ARG GH_CLIENT_SECRET

ENV JWT_SECRET_KEY=${JWT_SECRET_KEY}
ENV SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
ENV SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
ENV SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
ENV SUPPORT_EMAIL=${SUPPORT_EMAIL}
ENV APP_PASSWORD=${APP_PASSWORD}
ENV GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
ENV GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
ENV GH_CLIENT_ID=${GH_CLIENT_ID}
ENV GH_CLIENT_SECRET=${GH_CLIENT_SECRET}

COPY target/spring-email-tutorial-0.0.1-SNAPSHOT.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]
