FROM eclipse-temurin:17-jre-alpine

WORKDIR /app

# Build arguments to pass secrets/config
ARG JWT_SECRET_KEY
ARG SPRING_DATASOURCE_URL
ARG SPRING_DATASOURCE_USERNAME
ARG SPRING_DATASOURCE_PASSWORD
ARG SUPPORT_EMAIL
ARG APP_PASSWORD
ARG GOOGLE_CLIENT_ID
ARG GOOGLE_CLIENT_SECRET
ARG GH_CLIENT_ID
ARG GH_CLIENT_SECRET

# Pass secrets/config as environment variables
ENV JWT_SECRET_KEY=${JWT_SECRET_KEY} \
    SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL} \
    SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME} \
    SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD} \
    SUPPORT_EMAIL=${SUPPORT_EMAIL} \
    APP_PASSWORD=${APP_PASSWORD} \
    GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID} \
    GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET} \
    GH_CLIENT_ID=${GH_CLIENT_ID} \
    GH_CLIENT_SECRET=${GH_CLIENT_SECRET}

# Copy the compiled JAR file into the container
COPY target/spring-email-tutorial-0.0.1-SNAPSHOT.jar app.jar

# Expose the port the application will run on
EXPOSE 8080

# Run the JAR file when the container starts
ENTRYPOINT ["java", "-jar", "app.jar"]
